import { PlanetData } from './types';

export const PLANETS: PlanetData[] = [
  {
    id: 'mercury',
    name: 'Mercury',
    color: '#A5A5A5',
    size: 0.38,
    distance: 6,
    speed: 1.6,
    descriptionJA: '太陽に最も近い惑星です。表面はクレーターで覆われており、昼と夜の温度差が非常に激しいのが特徴です。',
    descriptionEN: 'The smallest planet in our solar system and closest to the Sun. It has a rocky surface covered with craters.',
  },
  {
    id: 'venus',
    name: 'Venus',
    color: '#E3BB76',
    size: 0.95,
    distance: 8.5,
    speed: 1.2,
    descriptionJA: '地球の兄弟星とも呼ばれますが、厚い二酸化炭素の大気に覆われ、表面温度は400度を超えます。',
    descriptionEN: 'Often called Earth\'s twin because of their similar size. Its thick atmosphere traps heat, making it the hottest planet.',
  },
  {
    id: 'earth',
    name: 'Earth',
    color: '#2271BD',
    size: 1,
    distance: 11,
    speed: 1.0,
    descriptionJA: '私たちが住む水の惑星です。生命が存在することが知られている唯一の天体です。',
    descriptionEN: 'Our home planet. It is the only place we know of so far that’s inhabited by living things.',
  },
  {
    id: 'mars',
    name: 'Mars',
    color: '#E27B58',
    size: 0.53,
    distance: 14,
    speed: 0.8,
    descriptionJA: '「赤い惑星」として知られています。かつては水が存在した痕跡があり、探査機による調査が進んでいます。',
    descriptionEN: 'Known as the Red Planet. It is a dusty, cold, desert world with a very thin atmosphere.',
  },
  {
    id: 'jupiter',
    name: 'Jupiter',
    color: '#C88B3A',
    size: 2.2,
    distance: 19,
    speed: 0.4,
    descriptionJA: '太陽系最大の巨大ガス惑星です。特徴的な縞模様と「大赤斑」と呼ばれる巨大な嵐があります。',
    descriptionEN: 'The largest planet in the solar system. It is a gas giant with a Great Red Spot, a storm that has raged for centuries.',
  },
  {
    id: 'saturn',
    name: 'Saturn',
    color: '#C5AB6E',
    size: 1.8,
    distance: 25,
    speed: 0.3,
    descriptionJA: '美しい環（リング）を持つことで有名な惑星です。比重が水より軽く、巨大なプールがあれば浮くと言われています。',
    descriptionEN: 'Famous for its prominent ring system. It is the second-largest planet and is composed mostly of hydrogen and helium.',
    hasRing: true,
  },
  {
    id: 'uranus',
    name: 'Uranus',
    color: '#93B8BE',
    size: 1.4,
    distance: 30,
    speed: 0.2,
    descriptionJA: '青白く輝く氷の巨大惑星です。自転軸がほぼ横倒しになっている珍しい特徴を持っています。',
    descriptionEN: 'An ice giant with a blue-green color from methane gas. Uniquely, it rotates on its side.',
  },
  {
    id: 'neptune',
    name: 'Neptune',
    color: '#3E54E8',
    size: 1.4,
    distance: 35,
    speed: 0.1,
    descriptionJA: '太陽系で最も外側を回る惑星です。非常に強い風が吹いており、美しい青色をしています。',
    descriptionEN: 'The most distant planet from the Sun. It is dark, cold, and whipped by supersonic winds.',
  },
];
